### ISSUE TITLE
Proposal for making NCG multi-tenant friendly

### ISSUE THREAD

**Issue by dpavlos** [ARGOeu/argo-ncg#2]
We can keep the basic functionality which in our case is all about fetching the topology from a GOCDB registry, consume the POEM profiles and create service check definitions according to the parameters that have been defined in ncg-metric-config json file (Until now this is a local configuration. As Daniel presented to us, POEM will handle this in the future). If there would be a need for additional functionality per tenant e.g ldap information source or sending notifications to a ticketing system/dashboard, perhaps we can expand the modular architecture of NCG and produce supplementary modules/packages that could be installed separately. Each module should have its own configuration file that ncg must be able to read. In that way we can reduce the complexity/confusion keeping the basic configurations clean and free of parameters that might be interested for one tenant but not for another.

Below is a list of some features that I stumbled upon while I was digging into the code. I believe we should not keep them included in the core functionality:
- VO references.
- MyProxy references.
- BDII references.
- WLCG references (directories, vars etc).
- Hacks for CREAMs,ARCs,SEs.
- ConfigPublish. This is for publishing nagios configs to message bus.
- Dead code regarding Nagios nodetypes (site,vo,ngi,project etc).
- Unicore probes.
- GGUS support. Remove any specific options that provide support for EGI's GGUS ticketing system.
- Dashboard support. Remove any specific options that provide support for EGI's ops portal.
- Remove notifications.
- Refactor Hash.pm for LocalMetrics. We should not distribute any probe specific configurations along
  with the base code. Nagios local metrics should be defined in a more generic way.
- GridMon references.
- GLITE version references.
- Remove BACKUP functionality.
- Probes type: all, local, remote. Keep a single local mode.
- Remove ncg-metric json default configs for opsmon and cloudmon from the rpm.
- Cleanup startup scripts.

Additionally there should be a mandatory tenant option in order to properly configure the necessary nagios commands for publishing to message bus.

**Comment by themiszamani** [comment]
https://jira.argo.grnet.gr/browse/ARGO-534
